{% set name = "sdjson" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sdjson-{{ version }}.tar.gz
  sha256: 1cb9fc9316b2fab479575f9a3102190da49f151be25a87e296a2316707b9e46e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - whey >=0.0.20
  run:
    - domdf-python-tools >=2.5.2
    - python >={{ python_min }}
    - typing-extensions >=3.7.4.3

test:
  imports:
    - sdjson
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/domdfcoding/singledispatch-json
  summary: Custom JSON Encoder for Python utilising functools.singledispatch to support custom encoders for both Python's built-in classes and user-created classes, without as much legwork.
  license: MIT
  license_file: LICENSE
  doc_url: https://singledispatch-json.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
